name: Release

permissions:
  contents: write

on:
  release:
    types: [created]
jobs:
  upload-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: discoidc
          target: x86_64-unknown-linux-gnu
          token: ${{ secrets.GITHUB_TOKEN }}
